# Huge, MEE SUSTech
# Email: zhuhu00@foxmail.com

version: '2.3'
services:
  cuda102-ros-ubuntu18:
    image: zhuhu/cuda102-ros-ubuntu18:0.2
    build: .

    command: lxterminal
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ../../panoptic:/root/catkin_ws/src/panoptic_ros
      # - ${DATASET_DIR}:/root/Dataset

    entrypoint: /ros_entrypoint.sh
    network_mode: host

volumes:
  cuda102-ros-ubuntu18: